services:
  postgres:
    image: postgres:16-alpine
    container_name: docker-postgres16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_skin_diagnosis
    ports:
      - "54321:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-python3.12
    volumes:
      - .:/app
    stdin_open: true  # Enable interactive mode.
    tty: true         # Allocate a pseudo-TTY
    command: python  # Starts Python interactive shell
    environment:
      - DB_NAME=db_skin_diagnosis
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
    depends_on:
      - postgres

volumes:
  postgres_data:
